name: Deploy Pipeline 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        type: environment

jobs:
  Deploy:
    
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ROLE: ${{ vars.ROLE }}
      ECR_REPO: ${{ vars.ECR_REPO }}
      tag: ${{ github.sha }}

    steps: 
      - name: Deploy
        run: |
          echo "Deploying the commit ${GITHUB_SHA:0:8} to development environment"
          echo "ROLE ARN: $ROLE"
          echo "Repo: $ECR_REPO"
          echo "tag: $tag"

